### ISSUE TITLE
auro-button: unable to import from Skypack

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-button#108]
## Describe the bug
I am unable to import auro-button from the Skypack CDN.

## To Reproduce
Open the following [CodePen](https://codepen.io/pen?&editors=0011&prefill_data_id=b3999af7-41b8-4f67-b398-6a5c8678972e) (linked from the [auro-button Skypack page](https://www.skypack.dev/view/@alaskaairux/auro-button)).

Note the console error: 

```
Uncaught Error: [Package Error] "lit-html" no dependency version info found. (Imported by "@alaskaairux/auro-button").
    <anonymous> https://cdn.skypack.dev/error/unknown:lit-html?from=@alaskaairux/auro-button:13
unknown:lit-html:13:7
    <anonymous> https://cdn.skypack.dev/error/unknown:lit-html?from=@alaskaairux/auro-button:13
    InnerModuleEvaluation self-hosted:2379
    InnerModuleEvaluation self-hosted:2379
    InnerModuleEvaluation self-hosted:2379
    InnerModuleEvaluation self-hosted:2379
    evaluation self-hosted:2330
```

The error links to [more details](https://cdn.skypack.dev/error/unknown:lit-html?from=@alaskaairux/auro-button):

```
/*
 * [Package Error] "lit-html" no dependency version info found. (Imported by "@alaskaairux/auro-button").
 *
 * The package "@alaskaairux/auro-button" depends on "lit-html" as a dependency,
 * but did not list any dependency version info in its package manifest.
 * Without this information, the CDN is unable to properly resolve this import.
 *
 * How to fix:
 *   - Let the "@alaskaairux/auro-button" package author know that "lit-html" needs to be included in their package.json manifest.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */
```

## Expected behavior
I can import auro-button from Skypack.

## Additional context
This doesn't happen with all Auro components. It seems that when we use lit-html (e.g. to import a directive), it needs to explicitly be defined as a dependency to work with Skypack. Adding lit-html to our dependencies may fix the error.

**Comment by blackfalcon** [comment]
In the Auro doc site I am doing this and it is working

```
    <script type="module">
      import alaskaairuxAuroButton from 'https://cdn.skypack.dev/@alaskaairux/auro-button@latest/dist/auro-button__bundled.js?min';
    </script>
```

**Comment by geoffrich** [comment]
That works because you're importing our pre-bundled file, so there's no direct lit-html import. However, the strength of Skypack is that it doesn't require the component to be pre-bundled and will [resolve imports for you](https://docs.skypack.dev/#more-packages-supported-less-code-served).

This means if you load multiple components from Skypack, there's no duplication of dependencies like lit-element. For example, here's a screenshot of the network tab on a page where I'm loading the unbundled loader and badge -- lit-element is only loaded once. Loading the bundled versions instead adds about 40KB since lit-element is duplicated in the bundles.
![image](https://user-images.githubusercontent.com/4992896/116133623-c4f13200-a683-11eb-904d-1ec8d427489c.png)

It would be nice if we could load the unbundled components from Skypack as well.

**Comment by blackfalcon** [comment]
Ok, so I don't know how to move forward. The scope of the bundled assets from the CDN is to ship the pre-bundled packages. 

I think what you are asking for is a way to pull from Skypack the individual asset sans the pre-bundling. if that is the case, then that is a whole new scope of the problem and not one solved inside this custom element. 

I'd argue that this needs to be leveled up to the generator and solved there as that is a new deliverable strategy.

**Comment by geoffrich** [comment]
This dropped off my radar, but circling back on this since it got linked in the combo issue.

The root issue here is we are importing directives from lit-html, but it is not defined as a dependency in the package.json. This happens to work because lit-html is a direct dependency of lit-element, but the LitElement docs say that lit-html should be a [direct dependency](https://lit-element.polymer-project.org/guide/templates#using-other-lit-html-features):

> To import features directly from lit-html, your project should add lit-html as a direct dependency. We recommend using the widest practical version range for lit-html, to minimize the chance of npm installing two different versions of lit-html:
>
> ```
> npm i lit-element@^2.0.0
> npm i lit-html@^1.0.0
> ```

We should likely do the same with any Auro component that imports directly from lit-html.

Adding lit-html as a direct dependency will make Auro compatible with Skypack, allowing us to import individual assets from Skypack without bundling.

**Comment by blackfalcon** [comment]
https://github.com/AlaskaAirlines/auro-button/commit/da4edec51e7cb1d50f7d6a2f09f60144960f1b07
