### ISSUE TITLE
v7.0-rc

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-button#126]
# User story

The scope of this story is to encompass the following open issues to be delivered. The following list is prioritized.

If there are NPM packages that need to be cleaned up.  Please add an issue and add it to this release.

## Outline subtasks or tasks.  These are grouped to avoid merge conflicts

- [ ] #109 
- [ ] #130
- [ ] #117

### Do these last

- [ ] #106 
- [x] #132

### Design

- [ ] https://github.com/AlaskaAirlines/auro-button/issues/134

### Prior to next major release 

It is **important that we communicate prior to the next major release** that we will be changing the npm namespace. See https://github.com/AlaskaAirlines/auro-radio/commit/2e894a0af517b633a4b24cbc2b3156cd96487d1d for the update to be used. 

## Versioning constraints 

While this will be a MAJOR release, mainly because of the new `@aurodesignsystem` npm namespace, the intent is that this update will be 100% backward compatible with regard to the API of the element. 

Task https://github.com/AlaskaAirlines/auro-button/issues/130 is the only potential issue, but it is assumed that this is a feature not widely used. Prior to release, we need to communicate that this feature is deprecated and expect its removal.

## Development process

This is a placeholder issue for all the issues to be in a single release. As each issue is put into play, please update the issue as IN PROGRESS and move it into the WIP column. Please leave this issue in TO DO until all linked issues are completed.

## Definition of “Done” (exit criteria)

This issue will be considered complete and all features released once all issues listed are considered complete.

**Comment by braven112** [comment]
Closing in favor of issues and milestones
