### ISSUE TITLE
Building the repo locally throws lint error, preventing commits

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-button#132]
## Describe the bug
When running `npm build` locally, a lint error is thrown:

```
src/style-ld.css
 11:3  ✖  "scss/no-global-function-names" has already been disabled   CssSyntaxError
```

The auto-generated `style-ld.css` file has the same disable line twice:

```css
auro-button-light {
  /**
 * Do not edit directly
 * Generated on Thu, 10 Jun 2021 19:44:30 GMT
 */
  /*
  Do not edit directly
  Generated on Thu, 10 Jun 2021 19:44:30 GMT
*/
  /* stylelint-disable scss/no-global-function-names */
  /* stylelint-disable scss/no-global-function-names */ }
```

I can't figure out where this line is coming from. It's not present in the original `style-ld.scss` file.

## To Reproduce
1. Clone the repo and run `npm install`
2. Run `npm run build`

## Expected behavior
There are no lint errors

## Desktop (please complete the following information):
 - OS: Windows 10 (using WSL 2)
 - Version: latest
 - npm: v6.14.13

## Additional context
This is blocking me from submitting a PR for another issue in this repo, since I can't commit.

**Comment by geoffrich** [comment]
As a side note, the linting is not currently being run for a PR build, allowing PRs to be merged with lint errors. Should we add `npm run lint` to the GH workflow?

**Comment by blackfalcon** [comment]
No, linters are not working with PR build, but they are supposed to run with a pre-commit hook. But it seems that things are getting past the goalie. 

I removed linters from the build command a while back, but I can't remember why https://github.com/AlaskaAirlines/WC-Generator/commit/0cbb79992095c3d261937982a491276ed9663aa0

Let's add this back into this PR and see what happens.

**Comment by geoffrich** [comment]
At least for auro-button, the `build` command still runs the CSS linter. At the moment I can't create a PR, since I can't commit anything due to the lint error.

Any idea why the lint error is there? I don't know what to change to resolve it since it's in a generated file. Searching the project for "no-global-function-names" doesn't turn up anything besides the file itself.

I could manually edit the generated file to get a commit through, but this will keep showing up until we fix the underlying issue.

**Comment by blackfalcon** [comment]
Working this issue into https://github.com/AlaskaAirlines/auro-button/issues/126 and making this work a priority.

**Comment by blackfalcon** [comment]
Looking at this it appears that this issue is only happening with the light DOM styles. This feature is on the list to be removed with the upcoming repo upgrades.

**Comment by braven112** [comment]
The plan is to remove light dom support from this repo in a future update.
