### ISSUE TITLE
auro-button: disabled state on auro-button doesn't reset

### ISSUE THREAD

**Issue by DZwell** [AlaskaAirlines/auro-button#138]
## Describe the bug
After setting the `auro-button`'s `disabled` attribute to `true` it never resets back to `false` and enables.

## Expected behavior
Button should re-enable

## Screenshots
![button-still-disabled](https://user-images.githubusercontent.com/10947475/137402531-2dc5c159-c81e-4d9f-a5b8-fd12d1c4ae67.gif)

I just realized my GIF focuses on the `auro-input` not the button. But still, you can see `this.state.isValid` toggle from true to false yet the button doesn't change. Here's a screenshot of what I'm doing with the button: 
![image](https://user-images.githubusercontent.com/10947475/137403115-c5b386fe-c316-4d7d-8d3e-8110b27a3f24.png)

## Desktop (please complete the following information):
 - OS: OSX
 - Browser Chrome

## Smartphone (please complete the following information):
 - Device: Mac

**Comment by blackfalcon** [comment]
Moved this issue from auro-icon to auro-button for the proper reference. 

I also want to add this link to [Auro's API best practices](https://auro.alaskaair.com/generator/define-api#:~:text=Boolean%20attributes%20should%20not%20use%20true%20or%20false%20as%20a%20value) for custom elements. These APIs will closely follow how HTML works as these are essentially HTML elements.
