### ISSUE TITLE
Edit accessibility guidelines for auro-button

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-button#141]
The tertiary button is not accessible. New guidelines behind this must be created. There should also be more guidance around when to use a tertiary button vs a hyperlink. Here are possible solutions.
* Underline the tertiary button
* Add an action icon as default (chevrons "> or <")

**Comment by braven112** [comment]
This would be a great time to add some do's and don't examples to the doc site.  

I think the original purpose or use case of the tertiary button was when it was sitting next to a primary button as a type of "cancel" or "go back" type of action.  If we were to go with an action icon in that scenario that might have an undesired effect of more "cancel's" if we don't also consider how to handle the primary button.  How do we handle the the primary button in that scenario?

I'm not sure if anyone knows where else we might be using a tertiary button in production to look at more scenario's?

**Comment by leeejune** [comment]
The scenario of having a primary and tertiary button was still deemed to be inaccessible. I submitted a research request to the UX team to test if users can tell if the tertiary button is a button when it's alone and when it's next to another button.

Do's and don't's will be needed to differentiate between hyperlinks and buttons as well. Not sure if we should start adding design guidelines now or add them when redesigning the doc site.

**Comment by braven112** [comment]
> The scenario of having a primary and tertiary button was still deemed to be inaccessible. 

Just to clarify, is the purpose of the research is to find out if this statement is true?

**Comment by leeejune** [comment]
@braven112 Yes.

**Comment by leeejune** [comment]
Researching with Pheobe and Araneetae to solve this. Options explored here: https://www.figma.com/file/CFVIEQkpeykfQejPppBili/Button?node-id=0%3A434

**Comment by leeejune** [comment]
Had conversation the UX research team. Will be conducting research (heat map) with ~50 participants and 6-8 interviews. Will be done in mid-Jan.

**Comment by leeejune** [comment]
User research has been completed. Results indicate that the current solution does not cause a problem for color blind users. Color blind users can identify/guess the color by differentiating shades of grey.

Next steps are to improve guidelines on when designers should use a tertiary button, tertiary button with an icon, and a hyperlink.

**Comment by leeejune** [comment]
Link to presentation: https://alaskaair-my.sharepoint.com/:p:/p/araneetae_guy/ER5X9rgy-5NBjuo-WjKJDfcB72IIEPi39LS0iWSO8lYyKA?e=4%3AK8SeT8&at=9&CID=69891a5d-3340-3834-959a-08975d518290

Next steps are in issue #155
