### ISSUE TITLE
Update design guidelines on tertiary auro-button and hyperlink

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-button#155]
# General Support Request

## Support request
Designers do not have any guidelines on how to choose between a tertiary button and a hyperlink.

## Possible Solution
According to user research, the current solution of buttons is accessible. Next steps are to write better guidelines on how to choose between a tertiary button and hyperlink. This can be done in "Do's and Don'ts" or general usage guidelines in the current doc site.

## Context
Issue #141 

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by blackfalcon** [comment]
In addition to this, I'd like to expand on this content update to include a11y specific pages to the Auro doc site button and hyperlink sections. 

The current demo pages speak specifically to a dev's ability to use the elements. I'd like to have content that speaks to the WHY things are done in order to address UX and a11y needs.

**Comment by blackfalcon** [comment]
This is contradicting? Specifically speaking to the use of the underlined links in each example. 

<img width="1076" alt="Screen Shot 2022-03-21 at 12 38 08 PM" src="https://user-images.githubusercontent.com/181089/159350713-ed2347a2-6d90-4c84-ab21-69270e93686b.png">

**Comment by leeejune** [comment]
@blackfalcon The left example is an example of a piece of content. To my understanding, the "no underline" hyperlink should only be used as a navigational element. The right example is a "header menu" so it makes sense to use a "no underline" hyperlink... if that is unclear I will edit the examples.

**Comment by leeejune** [comment]
Completed the decision tree after receiving feedback from the UI team.

**Comment by leeejune** [comment]
> I'd like to have content that speaks to the WHY things are done in order to address UX and a11y needs.

Can you elaborate on this more @blackfalcon? What are some examples of "things" that are done? Keyboard interactions? Visual elements?

**Comment by leeejune** [comment]
Accessibility guidelines related to design will be added to a README file.
