### ISSUE TITLE
Add background to onDark secondary button

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-button#156]
## Is your feature request related to a problem? Please describe.
The background on the onDark secondary button is transparent. This makes buttons placed on photos inaccessible.

## Describe the solution you'd like
Add a dark background to the onDark secondary button. Changes proposed on the blueprint: https://www.figma.com/file/CFVIEQkpeykfQejPppBili/Button?node-id=322%3A813

**Comment by blackfalcon** [comment]
@leeejune you want to make this update?

**Comment by leeejune** [comment]
@blackfalcon Sure!
