### ISSUE TITLE
auro-button: Slim tertiary style

### ISSUE THREAD

**Issue by jordanchang** [AlaskaAirlines/auro-button#159]
## Is your feature request related to a problem? Please describe.
Our designs occasionally call for a tertiary button to be aligned with other content.

Example design:
Note: It's styled like a link in the screenshot below, but I believe this is incorrect and should not have an underline.
![image](https://user-images.githubusercontent.com/3304352/169882882-4c9ab623-d59e-41e3-864c-4a458a7d8dab.png)

## Describe the solution you'd like
Allow devs to set padding for buttons to make the button slimmer.

## Describe alternatives you've considered
Using auro-hyperlink to achieve "no padding" effect.
![image](https://user-images.githubusercontent.com/3304352/169883220-828f2c77-0ab0-4f84-b1af-9f2740f1aa8d.png)

## Additional context
none

**Comment by blackfalcon** [comment]
@leeejune can you follow with @jordanchang and that team's designer to assist with this question.

**Comment by blackfalcon** [comment]
Please update this issue with any news as to the direction the design team wants to take.

**Comment by blackfalcon** [comment]
There is nothing wrong with having a 'slim' or small size buttons. I feel that Auro's lack of pill-sized buttons has lead to this. Look at the varients from Shoelace. https://shoelace.style/components/button

That being said, there is also a rapid misuse of the hyperlink affordance in areas where the interaction is to be a button. The slight UI differences between the tertiary auro-button and auro-hyperlink with role button are amazing slight. I'd like to see a button style created that eliminates the need for hyperlink role button. 

In addition to this, there continues to be feedback that the tertiary button is not accessible. Again I feel that if we had a button style that was not so similar to a hyperlink, we would not have that issue. But if we were to maintain a hyperlink style looking button, it should have an underline on hover to clearly denote its use.

**Comment by blackfalcon** [comment]
Design approved. Next step, @braven112 we need to prioritize this update. This issue is included in a v7.0 milestone, I'd like to see all this work ship in a single release. 

@leeejune is there any push from design to have this delivered fast?

**Comment by leeejune** [comment]
@blackfalcon Not necessarily, but I would like to have it released soon because designers seem to be eager to use it.

**Comment by leeejune** [comment]
Started this work on v.7.0-rc branch with @braven112
