### ISSUE TITLE
auro-button: add TypeScript declarations

### ISSUE THREAD

**Issue by alyssakreegsalaska** [AlaskaAirlines/auro-button#189]
## Is your feature request related to a problem? Please describe.
Multiple teams across E-Commerce use TypeScript and Auro.  The Auro libraries do not generate typings or declaration files - therefore, we have to add types ourselves.  There are many examples of repositories typing the auro components as "any".

Moving from "any" to a strongly typed auro interface will benefit all teams who use TypeScript by reducing the number of potential bugs with type-ohs.  It will also speed up our workflow when we upgrade the components, because we will be able to see where contracts changed and where we need to make manual updates.

Examples of repos typing auro components with "any":
- [Web-LoyaltyPromotion](https://github.com/Alaska-ECommerce/Web-LoyaltyPromotion/blob/3b96ecf74e2ffd642e8071a2ac04a91a7bfe23a6/src/react-app.env.d.ts)
- [booking-site](https://github.com/Alaska-ECommerce/booking-site/blob/fbd72f8529eac01bd9eea96c7d7c2724a7473bb0/declarations.d.ts)
- [flightchanges](https://github.com/Alaska-ECommerce/flightchanges-site-reactjs/blob/98b4b7a67129225d46255f525160a53fea528940/site/src/components/types.d.ts)
- [PreferenceCenter](https://github.com/Alaska-ECommerce/Web-PreferenceCenter/blob/108c2ecb3fb507004aefd64ab2fecfe4d9287746/preference-center/src/react-app-env.d.ts)
- [cool-runnings](https://github.com/Alaska-ECommerce/cool-runnings/blob/1028a74e5c96b380b39ce6ca5932b92df524fa95/client/src/jsx.d.ts)
- [100kChoice](https://github.com/Alaska-ECommerce/Web-100kChoice/blob/fc370e6b4f6787ada110ea1efb53c29bec2ad082/src/react-app-env.d.ts)

## Describe the solution you'd like
Add a declarations file to the auro libraries.  The types don't need to be tied to any framework (react, etc) but I would also like to update the examples of usage to show how to use those types.
How to do this -
- Add a file with the extension "d.ts" to the repository
- Make sure the new *.d.ts file is included in the build output directory
- Add a "types" reference to the package.json, with the path to the new *.d.ts file in the build output directory
- Maintain the *.d.ts file as contracts change

## Describe alternatives you've considered
- Rewrite auro in typescript :D 
- Maintain types outside of the auro component repositories, but this is a messier solution, as there will be multiple places to update as the contracts change, undoubtedly leading to confusion and mis-matched types

## Additional context
I am happy to help! I can submit a PR with an example.

**Comment by blackfalcon** [comment]
Researching this issue, generating typescript descriptions is a simple automated process we can add to any component. The big issue that we need to address is that this will not work with components where the default class is not exported, e.g. 99.999% of our current components including this one. 

The only element that lives up to this new spec is auro-hyperlink. The good news is that we have a plan to update all our components to fit this model. 

## Scope of work 

Update element to export component class by default. See the following PR for the exact work to be done. 

- https://github.com/AlaskaAirlines/auro-hyperlink/commit/bc8c594332e2ec6ff77453a443babacf13163883

Once completed, following [these instructions](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html) install the `tsc` process to generate the necessary TypeScript definition files

## Exit criteria 

This issue will be considered resolved once... 

1. the component has been updated to export the class by default
2. the TypeScript generator has been installed and there is a confirmed correct output

**Comment by blackfalcon** [comment]
The following issue was created to update the generator 

- https://github.com/AlaskaAirlines/WC-Generator/issues/374

**Comment by blackfalcon** [comment]
This work can be tracked by this issue and linked commit 

- https://github.com/AlaskaAirlines/auro-button/issues/206
