### ISSUE TITLE
Hover state color to be changed

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-button#227]
### Please verify the version of auro-button you have installed

@current 

### Please describe the bug

1. Go to https://auro.alaskaair.com/components/auro/button#:~:text=element%20be%20used.-,Default,-Example
2. Hover over the secondary button
3. See transparent background

### Reproducing the error on the docsite

This issue is reproducible on the Auro docsite

### Expected behavior

The hover color should be a combination of a white background (auro-color-background-lightest) and the hover color (auro-color-ui-bkg-hover-on-light).

When hovering over the button, it should not become transparent.

### Additional context

This issue is related to the back-to-top component.

**Comment by blackfalcon** [comment]
@leeejune is this a new spec or a regression? The work we did in the past was to update the tertiary button https://github.com/AlaskaAirlines/auro-button/commit/615d5d6606e3325e6b254911a3fe1ff6aed5d371

I can't find a reference to updating the secondary.

**Comment by braven112** [comment]
We'll need to finalize the background color for each hover state for each secondary button.

**Comment by Patrick-Daly-AA** [comment]
for future reference: https://www.geeksforgeeks.org/css-combine-background-image-with-gradient-overlay/

**Comment by jordanjones243** [comment]
Moving this ticket as blocked, as it is a part of a PR that has another blocked ticket: 
- https://github.com/AlaskaAirlines/auro-button/issues/229
