### ISSUE TITLE
auro-button: update on-dark tertiary button hover color

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-button#236]
### Is your feature request related to a problem? Please describe.

The tertiary button for the on-dark type should have the color `ds-color-ui-bkg-hover-inverse: #FFFFFF0F` (not sure if we should create `ds-color-base-white-opacity-06`).

### Describe the solution you'd like

Add the design token either in the `base` category or as a hexadecimal value.

### Additional context

This issue is related to https://github.com/AlaskaAirlines/AuroDesignTokens/issues/137

**Comment by jordanjones243** [comment]
This ticket was addressed as a part of this PR:
- https://github.com/AlaskaAirlines/auro-button/pull/228
