### ISSUE TITLE
auro-button: unstyled, icon only varient

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-button#252]
### Is your feature request related to a problem? Please describe.

Several of our other components use raw HTML <button> tags to create clickable elements and place an icon inside of them. These buttons are providing incomplete and inconsistent experiences.

### Describe the solution you'd like

I would like to see a varient of auro-button that that has no content styles and is for use with auro-icon as the slot content. This varient would simply pass down the state variations (e.g. `disabled`) to the slot content auro-icon and use the variant styles of that component.

This would simply the CSS code for parent components like Drawer and Dialog and provide that consistent user experience our customers expect.

### Describe alternatives you've considered

Do nothing and leave it as it is.

### Exit criteria

To be determined by triage process and the team.

**Comment by jordanjones243** [comment]
The work for this is a part of the v7.3.0 release and this ticket can therefore be closed.
