### ISSUE TITLE
Previously-disabled button is not focusable with the keyboard in IE11

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-button#77]
## Describe the bug
When auro-button is originally rendered with the disabled property and the property is removed, it is not focusable with the keyboard in IE11.

## To Reproduce
1. Render the following markup in IE11
```html
<auro-button>Make other button un-disabled</auro-button>
<auro-button onclick="alert('hello')" disabled>Free me!</auro-button>
<script>

	function setupClickListener() {
		const buttons = document.querySelectorAll('auro-button');
		buttons[0].addEventListener('click', function() {
			buttons[1].disabled = false;
		});
	}

	setupClickListener();
</script>
```
2. Tab to and trigger the first button to enable the second button
3. Attempt to tab to the now-enabled button. You are unable to focus it, though it is clickable and appears enabled.

This is also an issue with ods-button.

## Expected behavior
auro-button is focusable with the keyboard even when it was originally disabled.

## Environment
OS: Windows 10
Browser: IE11

## Additional context
This does not appear to be a problem in old Edge, for what it's worth.

**Comment by blackfalcon** [comment]
I will review this issue and work to repro it and prioritize accordingly.

**Comment by blackfalcon** [comment]
The priority level has been removed. We are in the process of deprecating all support for IE11 except for special use cases. If at such time we have dropped all IE11 support and this issue has not yet been resolved, it will be closed with a `no fix`.

**Comment by blackfalcon** [comment]
This issue no longer requires a fix as IE11 will no longer be supported.
