### ISSUE TITLE
auro-button: active state

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-button#88]
## Is your feature request related to a problem? Please describe.
When submitting a form, we need a way to indicate to the user that the form is submitting. Currently, we simply disable the button.

## Describe the solution you'd like
An active state for `auro-button` to use when forms are being submitted. `ods-button` had an active state that triggered a dancing dots animation and made the button non-clickable.

**Comment by vidalmenAS** [comment]
@jason-capsule42 here is that spec sheet for loader button. as a reminder: we're just repurposing our [auro-loader ](https://auro.alaskaair.com/components/auro/loader)for this.let me know if u have any questions. Thanks!
[Loading Button.pdf](https://github.com/AlaskaAirlines/auro-button/files/6039248/Loading.Button.pdf)

**Comment by jason-capsule42** [comment]
@vidalmenAS I want to be sure I am clear - you want the button text to be replaced with the loader entirely when this state is active on the button?

**Comment by vidalmenAS** [comment]
@jason-capsule42 i wanted to bring the loader into the button when the state is active (loading) so this would involve sizing it to the spec and changing its color for both light and dark. let me know if there is anything else I need to add to that PDF. also happy to meet and discuss

**Comment by blackfalcon** [comment]
Looking at the comp, we don't have a `pulse` loader at that size. This update will require an update to auro-loader prior to the update to auro-button. 

https://auro.alaskaair.com/components/auro/loader

**Comment by blackfalcon** [comment]
We do not have a token for `#e9fcff`. What is this color? Providing redlines with Design Token specifications is appreciated. 

The pulse design provided is not a color spec currently supported by the auro-loader element.

**Comment by jason-capsule42** [comment]
@blackfalcon I already have a meeting scheduled with Vidal to review some of these implementation details.

**Comment by vidalmenAS** [comment]
@blackfalcon  @jason-capsule42  - caught me. was trying to maintain both tint and contrast but lets just replace with the existing version of the white loader

**Comment by blackfalcon** [comment]
![busted](https://thumbs.gfycat.com/DapperRemorsefulAtlanticridleyturtle-mobile.jpg)

**Comment by blackfalcon** [comment]
Please push feature branch and create DRAFT PR.
